# Generated by Django 6.0.6 on 2026-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
