# Generated by Django 6.0.6 on 2026-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_coffee_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='stock',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
